=== artur-hurynovich/java-ee-project/mus-site/src/main/resources/authsSchema.xsd
<?xml version="1.0" encoding="UTF-8"?>
<schema xmlns = "http://www.w3.org/2001/XMLSchema" 
	targetNamespace = "http://www.hurynovich.com/authsSchema" 
	xmlns:tns = "http://www.hurynovich.com/authsSchema">
	<complexType name = "Auth">
		<sequence>
			<element name = "url" type = "string"  />
			<element name = "role" type = "tns:roleType" minOccurs = "1" maxOccurs = "3" />
		</sequence>
	</complexType>
	<simpleType name = "roleType">
		<restriction base = "string">
			<enumeration value = "USER" />
			<enumeration value = "MANAGER" />
			<enumeration value = "ADMIN" />
		</restriction>
	</simpleType>
    <element name = "auths">
    	<complexType>
    		<sequence>
    			<element name = "auth" type = "tns:Auth" minOccurs = "1" maxOccurs = "unbounded" />
    		</sequence>
    	</complexType>
    </element>
</schema>

=== artur-hurynovich/java-ee-project/mus-site/src/main/resources/auths.xml
<?xml version="1.0" encoding="UTF-8"?>
<tns:auths xmlns:tns = "http://www.hurynovich.com/authsSchema" 
	xmlns:xsi = "http://www.w3.org/2001/XMLSchema-instance" 
	xsi:schemaLocation = "http://www.hurynovich.com/authsSchema authsSchema.xsd ">
	<auth>
		<url>instruments_rate</url>
		<role>USER</role>
		<role>MANAGER</role>
		<role>ADMIN</role>
	</auth>
	<auth>
		<url>reviews_new</url>
		<role>MANAGER</role>
		<role>ADMIN</role>
	</auth>
	<auth>
		<url>reviews_edit</url>
		<role>MANAGER</role>
		<role>ADMIN</role>
	</auth>
	<auth>
		<url>reviews_delete</url>
		<role>MANAGER</role>
		<role>ADMIN</role>
	</auth>
	<auth>
		<url>instruments_new</url>
		<role>MANAGER</role>
		<role>ADMIN</role>
	</auth>
	<auth>
		<url>instruments_delete</url>
		<role>MANAGER</role>
		<role>ADMIN</role>
	</auth>
	<auth>
		<url>instruments_new_group</url>
		<role>ADMIN</role>
	</auth>
	<auth>
		<url>instruments_new_subgroup</url>
		<role>ADMIN</role>
	</auth>
	<auth>
		<url>instruments_delete_group</url>
		<role>ADMIN</role>
	</auth>
	<auth>
		<url>instruments_delete_subgroup</url>
		<role>ADMIN</role>
	</auth>
	<auth>
		<url>profile_change_role</url>
		<role>ADMIN</role>
	</auth>
</tns:auths>
