=== artur-hurynovich/java-ee-project/mus-site/src/main/resources/commandsSchema.xsd
<?xml version="1.0" encoding="UTF-8"?>
<schema xmlns = "http://www.w3.org/2001/XMLSchema" 
	targetNamespace = "http://www.hurynovich.com/commandsSchema" 
	xmlns:tns = "http://www.hurynovich.com/commandsSchema">
	<complexType name = "Command">
		<sequence>
			<element name = "commandName" type = "string" />
    		<element name = "commandClass" type = "string" />
		</sequence>
	</complexType>
    <element name = "commands">
    	<complexType>
    		<sequence>
    			<element name = "command" type = "tns:Command" minOccurs = "1" maxOccurs = "unbounded" />
    		</sequence>
    	</complexType>
    </element>
</schema>

=== artur-hurynovich/java-ee-project/mus-site/src/main/resources/commands.xml
<?xml version="1.0" encoding="UTF-8"?>
<tns:commands xmlns:tns = "http://www.hurynovich.com/commandsSchema" 
	xmlns:xsi = "http://www.w3.org/2001/XMLSchema-instance" 
	xsi:schemaLocation = "http://www.hurynovich.com/commandsSchema commandsSchema.xsd ">
	<!-- Page commands -->
  	<command>
    	<commandName>reviews_new_page</commandName>
    	<commandClass>com.hurynovich.mus_site.controller.command.impl.page.review.ReviewsNewPageCommand</commandClass>
  	</command>
  	<command>
    	<commandName>reviews_new_success_page</commandName>
    	<commandClass>com.hurynovich.mus_site.controller.command.impl.page.review.ReviewsNewSuccessPageCommand</commandClass>
  	</command>
  	<command>
    	<commandName>reviews_page</commandName>
    	<commandClass>com.hurynovich.mus_site.controller.command.impl.page.review.ReviewsPageCommand</commandClass>
  	</command>
  	<command>
    	<commandName>reviews_by_hashtags_page</commandName>
    	<commandClass>com.hurynovich.mus_site.controller.command.impl.page.review.ReviewsByHashtagsPageCommand</commandClass>
  	</command>
  	<command>
    	<commandName>reviews_read_page</commandName>
    	<commandClass>com.hurynovich.mus_site.controller.command.impl.page.review.ReviewsReadPageCommand</commandClass>
  	</command>
  	<command>
    	<commandName>reviews_edit_page</commandName>
    	<commandClass>com.hurynovich.mus_site.controller.command.impl.page.review.ReviewsEditPageCommand</commandClass>
  	</command>
  	<command>
    	<commandName>reviews_delete_success_page</commandName>
    	<commandClass>com.hurynovich.mus_site.controller.command.impl.page.review.ReviewsDeleteSuccessPageCommand</commandClass>
  	</command>
  	<command>
    	<commandName>instruments_new_group_page</commandName>
    	<commandClass>com.hurynovich.mus_site.controller.command.impl.page.instrument.InstrumentsNewGroupPageCommand</commandClass>
  	</command>
  	<command>
    	<commandName>instruments_new_group_success_page</commandName>
    	<commandClass>com.hurynovich.mus_site.controller.command.impl.page.instrument.InstrumentsNewGroupSuccessPageCommand</commandClass>
  	</command>
  	<command>
    	<commandName>instruments_new_subgroup_page</commandName>
    	<commandClass>com.hurynovich.mus_site.controller.command.impl.page.instrument.InstrumentsNewSubgroupPageCommand</commandClass>
  	</command>
  	<command>
    	<commandName>instruments_new_subgroup_continue_page</commandName>
    	<commandClass>com.hurynovich.mus_site.controller.command.impl.page.instrument.InstrumentsNewSubgroupContinuePageCommand</commandClass>
  	</command>
  	<command>
    	<commandName>instruments_new_subgroup_success_page</commandName>
    	<commandClass>com.hurynovich.mus_site.controller.command.impl.page.instrument.InstrumentsNewSubgroupSuccessPageCommand</commandClass>
  	</command>
  	<command>
    	<commandName>instruments_new_page</commandName>
    	<commandClass>com.hurynovich.mus_site.controller.command.impl.page.instrument.InstrumentsNewPageCommand</commandClass>
  	</command>
  	<command>
    	<commandName>instruments_new_continue_page</commandName>
    	<commandClass>com.hurynovich.mus_site.controller.command.impl.page.instrument.InstrumentsNewContinuePageCommand</commandClass>
  	</command>
  	<command>
    	<commandName>instruments_new_success_page</commandName>
    	<commandClass>com.hurynovich.mus_site.controller.command.impl.page.instrument.InstrumentsNewSuccessPageCommand</commandClass>
  	</command>
  	<command>
    	<commandName>instruments_page</commandName>
    	<commandClass>com.hurynovich.mus_site.controller.command.impl.page.instrument.InstrumentsPageCommand</commandClass>
  	</command>
  	<command>
  		<commandName>instruments_subgroup_page</commandName>
  		<commandClass>com.hurynovich.mus_site.controller.command.impl.page.instrument.InstrumentsSubgroupPageCommand</commandClass>
  	</command>
  	<command>
    	<commandName>instruments_subgroup_filter_page</commandName>
    	<commandClass>com.hurynovich.mus_site.controller.command.impl.page.instrument.InstrumentsSubgroupFilterPageCommand</commandClass>
  	</command>
  	<command>
  		<commandName>instruments_read_page</commandName>
  		<commandClass>com.hurynovich.mus_site.controller.command.impl.page.instrument.InstrumentsReadPageCommand</commandClass>
  	</command>
  	<command>
    	<commandName>instruments_manage_groups_page</commandName>
    	<commandClass>com.hurynovich.mus_site.controller.command.impl.page.instrument.InstrumentsManageGroupsPageCommand</commandClass>
  	</command>
  	<command>
    	<commandName>instruments_delete_group_page</commandName>
    	<commandClass>com.hurynovich.mus_site.controller.command.impl.page.instrument.InstrumentsDeleteGroupPageCommand</commandClass>
  	</command>
  	<command>
    	<commandName>instruments_delete_group_success_page</commandName>
    	<commandClass>com.hurynovich.mus_site.controller.command.impl.page.instrument.InstrumentsDeleteGroupSuccessPageCommand</commandClass>
  	</command>
  	<command>
    	<commandName>instruments_delete_subgroup_page</commandName>
    	<commandClass>com.hurynovich.mus_site.controller.command.impl.page.instrument.InstrumentsDeleteSubgroupPageCommand</commandClass>
  	</command>
  	<command>
    	<commandName>instruments_delete_subgroup_success_page</commandName>
    	<commandClass>com.hurynovich.mus_site.controller.command.impl.page.instrument.InstrumentsDeleteSubgroupSuccessPageCommand</commandClass>
  	</command>
  	<command>
    	<commandName>instruments_delete_success_page</commandName>
    	<commandClass>com.hurynovich.mus_site.controller.command.impl.page.instrument.InstrumentsDeleteSuccessPageCommand</commandClass>
  	</command>
  	<command>
    	<commandName>instruments_rate_success_page</commandName>
    	<commandClass>com.hurynovich.mus_site.controller.command.impl.page.instrument.InstrumentsRateSuccessPageCommand</commandClass>
  	</command>
  	<command>
    	<commandName>profile_page</commandName>
    	<commandClass>com.hurynovich.mus_site.controller.command.impl.page.profile.ProfilePageCommand</commandClass>
  	</command>
  	<command>
    	<commandName>profile_registration_page</commandName>
    	<commandClass>com.hurynovich.mus_site.controller.command.impl.page.profile.ProfileRegistrationPageCommand</commandClass>
  	</command>
  	<command>
    	<commandName>profile_login_page</commandName>
    	<commandClass>com.hurynovich.mus_site.controller.command.impl.page.profile.ProfileLoginPageCommand</commandClass>
  	</command>
  	<command>
    	<commandName>profile_registration_success_page</commandName>
    	<commandClass>com.hurynovich.mus_site.controller.command.impl.page.profile.ProfileRegistrationSuccessPageCommand</commandClass>
  	</command>
  	<command>
    	<commandName>profile_change_role_page</commandName>
    	<commandClass>com.hurynovich.mus_site.controller.command.impl.page.profile.ProfileChangeRolePageCommand</commandClass>
  	</command>
  	<command>
    	<commandName>profile_change_role_continue_page</commandName>
    	<commandClass>com.hurynovich.mus_site.controller.command.impl.page.profile.ProfileChangeRoleContinuePageCommand</commandClass>
  	</command>
  	<command>
    	<commandName>profile_change_role_success_page</commandName>
    	<commandClass>com.hurynovich.mus_site.controller.command.impl.page.profile.ProfileChangeRoleSuccessPageCommand</commandClass>
  	</command>
  	<command>
    	<commandName>error_page</commandName>
    	<commandClass>com.hurynovich.mus_site.controller.command.impl.page.ErrorPageCommand</commandClass>
  	</command>
  	<!-- Action commands -->
  	<command>
    	<commandName>reviews_new</commandName>
    	<commandClass>com.hurynovich.mus_site.controller.command.impl.review.ReviewsNewCommand</commandClass>
  	</command>
  	<command>
    	<commandName>reviews_edit</commandName>
    	<commandClass>com.hurynovich.mus_site.controller.command.impl.review.ReviewsEditCommand</commandClass>
  	</command>
  	<command>
    	<commandName>reviews_delete</commandName>
    	<commandClass>com.hurynovich.mus_site.controller.command.impl.review.ReviewsDeleteCommand</commandClass>
  	</command>
  	<command>
    	<commandName>instruments_new</commandName>
    	<commandClass>com.hurynovich.mus_site.controller.command.impl.instrument.InstrumentsNewCommand</commandClass>
  	</command>
  	<command>
    	<commandName>instruments_new_subgroup</commandName>
    	<commandClass>com.hurynovich.mus_site.controller.command.impl.instrument.InstrumentsNewSubgroupCommand</commandClass>
  	</command>
  	<command>
    	<commandName>instruments_new_group</commandName>
    	<commandClass>com.hurynovich.mus_site.controller.command.impl.instrument.InstrumentsNewGroupCommand</commandClass>
  	</command>
  	<command>
    	<commandName>instruments_rate</commandName>
    	<commandClass>com.hurynovich.mus_site.controller.command.impl.instrument.InstrumentsRateCommand</commandClass>
  	</command>
  	<command>
  		<commandName>instruments_delete</commandName>
  		<commandClass>com.hurynovich.mus_site.controller.command.impl.instrument.InstrumentsDeleteCommand</commandClass>
  	</command>
  	<command>
    	<commandName>instruments_delete_subgroup</commandName>
    	<commandClass>com.hurynovich.mus_site.controller.command.impl.instrument.InstrumentsDeleteSubgroupCommand</commandClass>
  	</command>
  	<command>
    	<commandName>instruments_delete_group</commandName>
    	<commandClass>com.hurynovich.mus_site.controller.command.impl.instrument.InstrumentsDeleteGroupCommand</commandClass>
  	</command>
  	<command>
    	<commandName>profile_registration</commandName>
    	<commandClass>com.hurynovich.mus_site.controller.command.impl.profile.ProfileRegistrationCommand</commandClass>
  	</command>
  	<command>
    	<commandName>profile_login</commandName>
